project:
  type: website

website:
  title: "Statistical Skier"
  site-url: "https://statisticalskier.netlify.app/"
  description: "Statistical commentary on cross country skiing"
  navbar:
    logo: skierlogo-chart.png
    right:
      - about.qmd
      - icon: graph-up
        href: https://statisticalskier.shinyapps.io/StatisticalSkierApp/
      - icon: mastodon
        href: https://mastodon.social/@joranelias
      - icon: github
        href: https://github.com/joranE
      - icon: linkedin
        href: https://www.linkedin.com/in/joran-elias-ab1548255/
      - icon: rss
        href: index.xml

format:
  html:
    theme: darkly
    css: styles.css

editor: source

execute: 
  freeze: auto
  echo: false
  warning: false

