project:
  type: website

website:
  title: "Statistical Skier"
  navbar:
    logo: skierlogo-chart.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joranE
      - icon: mastodon
        href: https://mastodon.social/@joranelias
format:
  html:
    theme: darkly
    css: styles.css

editor: source

