---
title: "Toblach 20k Skiathlon Race Snapshots"
author: "Joran Elias"
date: "2024-12-31"
categories: [tour de ski,distance,race snapshots,interval start,toblach, freestyle]
draft: false
---

```{r pkgs}
library(tidyverse)
library(statskier2)

statskier_connect()
ev_id_m <- 20534
ev_id_w <- 20535
```

```{r gen-snap}
p_men <- 
  race_snapshot_dst(
    event_id = ev_id_m,
    title = "Men's Lillehammer 20k Skiathlon",
    reduced = TRUE
  )
p_wom <- 
  race_snapshot_dst(
    event_id = ev_id_w,
    title = "Women's Lillehammer 20k Skiathlon",
    reduced = TRUE
  )
```

### Race Snapshots
#### Men
```{r men-snap,fig.height=12,fig.width=8}
p_men$plot
```

#### Women
```{r wom-snap,fig.height=12,fig.width=8}
p_wom$plot
```

### Pacing Plots
Only a single lap, so no pacing plots.
```{r pacing-plots}
# m_pac <- dst_pacing_plot(.eventid = ev_id_m,
#                          .subset = rank <= 9,
#                          n_laps = 2,
#                          #omit_splits = 2.3,
#                          collapse_short_seg = FALSE,
#                          title_text = "Men's Lillehammer 10k Freestyle",
#                          skip_first_split = FALSE)
# w_pac <- dst_pacing_plot(.eventid = ev_id_w,
#                          .subset = rank <= 9,
#                          n_laps = 2,
#                          #omit_splits = 2.3,
#                          collapse_short_seg = FALSE,
#                          title_text = "Women's Lillehammer 10k Freestyle",
#                          skip_first_split = FALSE)
```
#### Men
```{r men-pacing}
#m_pac$plot
```

#### Women
```{r wom-pacing}
#w_pac$plot
```

### Splits
```{r splits}
wom_splits <- dst_split_plot(.eventid = ev_id_w,ref_split = 1)
men_splits <- dst_split_plot(.eventid = ev_id_m,ref_split = 1)
```

#### Men
```{r men-splits,fig.height=10,fig.width=10}
men_splits$final_plot
```

#### Women
```{r wom-splits,fig.height=10,fig.width=10}
wom_splits$final_plot
```