---
title: "Falun 20k Freestyle Mass Start Race Snapshots"
author: "Joran Elias"
date: "2024-03-17"
categories: [world cup,distance,race snapshots,mass start,freestyle,falun]
draft: false
---

```{r pkgs,message=FALSE}
library(tidyverse)
library(glue)
library(statskier2)

statskier_connect()
ev_id_m <- 20091
ev_id_w <- 20090

race_location <- 'Falun'
race_length <- '20'
race_tech <- 'Freestyle'
race_format <- 'Mass'

n_laps_men <- 8
n_laps_wom <- 8
```

```{r gen-snap}
p_men <- race_snapshot_dst(event_id = ev_id_m,
                           title = glue("Men's {location} {length}k {tech} {format}",
                                        location = race_location,
                                        length = race_length,
                                        tech = race_tech,
                                        format = race_format),
                           reduced = TRUE)
p_wom <- race_snapshot_dst(event_id = ev_id_w,
                           title = glue("Women's {location} {length}k {tech} {format}",
                                        location = race_location,
                                        length = race_length,
                                        tech = race_tech,
                                        format = race_format),
                           reduced = TRUE)
```

### Race Snapshots
#### Men
```{r men-snap,fig.height=12,fig.width=8}
p_men$plot
```

#### Women
```{r wom-snap,fig.height=12,fig.width=8}
p_wom$plot
```

### Pacing Plots
```{r pacing-plots}
m_pac <- dst_pacing_plot(.eventid = ev_id_m,
                         .subset = rank <= 9,
                         n_laps = n_laps_men,
                         #omit_splits = 2.3,
                         collapse_short_seg = FALSE,
                         title_text = glue("Men's {location} {length}k {tech} {format}",
                                           location = race_location,
                                           length = race_length,
                                           tech = race_tech,
                                           format = race_format),
                         skip_first_split = FALSE)
w_pac <- dst_pacing_plot(.eventid = ev_id_w,
                         .subset = rank <= 9,
                         n_laps = n_laps_wom,
                         #omit_splits = 2.3,
                         collapse_short_seg = FALSE,
                         title_text = glue("Women's {location} {length}k {tech} {format}",
                                           location = race_location,
                                           length = race_length,
                                           tech = race_tech,
                                           format = race_format),
                         skip_first_split = FALSE)
```
#### Men
```{r men-pacing,fig.height=8,fig.width=8}
m_pac$plot + theme(axis.text.x = element_text(size = 14 / .pt))
```

#### Women
```{r wom-pacing,fig.width=8,fig.height=8}
w_pac$plot + theme(axis.text.x = element_text(size = 14 / .pt))
```

### Splits
```{r splits}
wom_splits <- dst_split_plot(.eventid = ev_id_w,ref_split = 1)
men_splits <- dst_split_plot(.eventid = ev_id_m,ref_split = 1)
```

#### Men
```{r men-splits,fig.height=10,fig.width=10}
men_splits$final_plot
```

#### Women
```{r wom-splits,fig.height=10,fig.width=10}
wom_splits$final_plot
```