---
title: "Trondheim 10k Classic Predictions"
author: "Joran Elias"
date: "2023-12-16"
categories: [world cup,distance,classic,interval start,predictions,trondheim]
draft: false
---

```{r pkgs,message=FALSE}
library(tidyverse)
library(statskier2)
library(gt)
library(gtExtras)
library(ggpubr)

theme_set(theme_bw())
```

### Predictions
Haha...I wonder how much I'd have to put my thumb on the scale for this page 
rank method to stop picking Friday to win? I mean, if she does bad enough for 
long enough it will catch up eventually.

```{r pred-data}
location <- "Trondheim"
len <- "10k"
tech <- "Classic"
mens_preds <- 
  readr::read_csv(file = '2023-12-17_men_cl_dst_trondheim.csv',
                  show_col_types = FALSE)
womens_preds <- 
  readr::read_csv(file = '2023-12-17_wom_cl_dst_trondheim.csv',
                  show_col_types = FALSE)
```

#### Men's 10k Classic Predictions
```{r tbl-men}
mens_preds |> 
  select(-compid) |> 
  gt() |> 
  tab_header(title = glue::glue("{loc} {len} {tech}",loc = location,len = len,tech = tech),
             subtitle = "Men") |> 
  opt_align_table_header(align = 'left') |> 
  tab_caption(caption = "") |> 
  tab_options(
    table.font.size = 9,
    ihtml.active = TRUE,
    ihtml.use_pagination = TRUE,
    ihtml.use_compact_mode = TRUE,
    ihtml.use_highlight = TRUE
  ) |> 
  cols_label(
    fisid = 'FIS Code',
    name = 'Name',
    page_rank = 'Predicted PR',
    page_rank_pos = 'Predicted Finish') |> 
  fmt_number(columns = page_rank,decimals = 4) |> 
  gt_plt_bar(column = page_rank) 
```

#### Women's 10k Classic Predictions
```{r tbl-wom}
womens_preds |> 
  select(-compid) |> 
  gt() |> 
  tab_header(title = glue::glue("{loc} {len} {tech}",loc = location,len = len,tech = tech),
             subtitle = "Women") |>
  opt_align_table_header(align = 'left') |> 
  tab_caption(caption = "") |> 
  tab_options(
    table.font.size = 9,
    ihtml.active = TRUE,
    ihtml.use_pagination = TRUE,
    ihtml.use_compact_mode = TRUE,
    ihtml.use_highlight = TRUE
  ) |> 
  cols_label(
    fisid = 'FIS Code',
    name = 'Name',
    page_rank = 'Predicted PR',
    page_rank_pos = 'Predicted Finish') |> 
  fmt_number(columns = page_rank,decimals = 4) |> 
  gt_plt_bar(column = page_rank)
```

